### ISSUE TITLE
SingletonAttribute from infra project not recognized during build

### ISSUE THREAD

**Issue by xstof** [dolittle-samples/eCommerce#1]
See: https://github.com/dolittle-samples/eCommerce/blob/f3b2699009d2480aa76caa630fc5d44166a45d70/Source/Common/Infrastructure.Web/Hubs.cs#L8

Should this come from `Dolittle.Lifecycle` then a reference should probably be added within `Infrastructure.Web.csproj` ?

On a similar note; the build also seems to dislike `builder.Bind<ICallContext>().To<DefaultCallContext>();` within `NullBindings` on both Bounded Contexts

**Comment by einari** [comment]
Relates to #4
We've had some namespace changes lately.  For our 2.0.0 release to go out, we need this sample compiling and working. Not complete - but at least just working :)
