### ISSUE TITLE
Compile time errors

### ISSUE THREAD

**Issue by jwillmer** [dolittle-samples/eCommerce#3]
I followed the README to setup the project and run into the following errors:
![error](https://user-images.githubusercontent.com/1503577/46529520-ff610c80-c896-11e8-83bb-cb229a8b8994.png)

**Comment by einari** [comment]
Breaking change due to changes in namespaces lately - we'll deal with this in #3

**Comment by woksin** [comment]
@einari is this dealt with? Can we close this?
